export const SAVE_PROPOSAL_FORM = "SAVE_PROPOSAL_FORM";
export const SAVE_PROPOSAL_FORM_SUCCESS = "SAVE_PROPOSAL_FORM_SUCCESS";
export const SAVE_PROPOSAL_FORM_ERROR = "SAVE_PROPOSAL_FORM_ERROR";
export const SAVE_PROPOSAL_FORM_RESET = "SAVE_PROPOSAL_FORM_RESET";
export const GET_BUYER_PROPOSAL_RECORDS = 'GET_BUYER_PROPOSAL_RECORDS';
export const BUYER_PROPOSAL_SUCCESS = 'BUYER_PROPOSAL_SUCCESS';
export const BUYER_PROPOSAL_ERROR = 'BUYER_PROPOSAL_ERROR';
