export const SAVE_PROPOSAL_FORM = "SAVE_PROPOSAL_FORM";
export const SAVE_PROPOSAL_FORM_SUCCESS = "SAVE_PROPOSAL_FORM_SUCCESS";
export const SAVE_PROPOSAL_FORM_ERROR = "SAVE_PROPOSAL_FORM_ERROR";
export const SAVE_PROPOSAL_FORM_RESET = "SAVE_PROPOSAL_FORM_RESET";
