export const SAVE_PROPOSAL_FORM_API = "SAVE_PROPOSAL_FORM_API";
export const SAVE_PROPOSAL_FORM_API_SUCCESS = "SAVE_PROPOSAL_FORM_API_SUCCESS";
export const SAVE_PROPOSAL_FORM_API_ERROR = "SAVE_PROPOSAL_FORM_API_ERROR";
export const SAVE_PROPOSAL_FORM_API_RESET = "SAVE_PROPOSAL_FORM_API_RESET";

export const PUBLISH_PROPOSAL_API = "PUBLISH_PROPOSAL_API";
export const PUBLISH_PROPOSAL_API_SUCCESS = "PUBLISH_PROPOSAL_API_SUCCESS";
export const PUBLISH_PROPOSAL_API_ERROR = "PUBLISH_PROPOSAL_API_ERROR";
export const PUBLISH_PROPOSAL__API_RESET = "PUBLISH_PROPOSAL__API_RESET";

export const SAVE_PROPOSAL_FORM = "SAVE_PROPOSAL_FORM";
export const SAVE_PROPOSAL_FORM_SUCCESS = "SAVE_PROPOSAL_FORM_SUCCESS";
export const SAVE_PROPOSAL_FORM_ERROR = "SAVE_PROPOSAL_FORM_ERROR";

export const PUBLISH_PROPOSAL_QUERY = "PUBLISH_PROPOSAL_QUERY";

export const PUBLISH_PROPOSAL_SUCCESS = "PUBLISH_PROPOSAL_SUCCESS";
export const PUBLISH_PROPOSAL_ERROR = "PUBLISH_PROPOSAL_ERROR";

export const GET_PROPOSAL = "GET_PROPOSAL";
export const GET_PROPOSAL_ERROR = "GET_PROPOSAL_ERROR";
export const GET_PROPOSAL_SUCCESS = "GET_PROPOSAL_SUCCESS";

export const GET_PROPOSAL_INFO = "GET_PROPOSAL_INFO";
export const GET_PROPOSAL_INFO_ERROR = "GET_PROPOSAL_INFO_ERROR";
export const GET_PROPOSAL_INFO_SUCCESS = "GET_PROPOSAL_INFO_SUCCESS";

export const SAVE_BID_QUERY = "SAVE_BID_QUERY";

export const SAVE_BID_SUCCESS = "SAVE_BID_SUCCESS";

export const SAVE_BID_ERROR = "SAVE_BID_ERROR";

export const PUBLISH_BID_QUERY = "PUBLISH_BID_QUERY";

export const PUBLISH_BID_SUCCESS = "PUBLISH_BID_SUCCESS";
export const PUBLISH_BID_ERROR = "PUBLISH_BID_ERROR";
export const GET_BIDS_BY_SELLER_QUERY = "GET_BIDS_BY_SELLER_QUERY";
export const BIDS_BY_SELLER_SUCCESS = "BIDS_BY_SELLER_SUCCESS";
export const BIDS_BY_SELLER_ERROR = "BIDS_BY_SELLER_ERROR";
export const GET_BIDS_INFO_QUERY = "GET_BIDS_INFO_QUERY";
export const GET_BID_INFO_SUCCESS = "GET_BID_INFO_SUCCESS";
export const GET_BID_INFO_ERROR = "GET_BID_INFO_ERROR";






