export const SAVE_PROPOSAL_FORM = "SAVE_PROPOSAL_FORM";
export const SAVE_PROPOSAL_FORM_SUCCESS = "SAVE_PROPOSAL_FORM_SUCCESS";
export const SAVE_PROPOSAL_FORM_ERROR = "SAVE_PROPOSAL_FORM_ERROR";
export const PROPOSAL_FETCH_API = "PROPOSAL_FETCH_API";
export const PROPOSAL_FETCH_ERROR = "PROPOSAL_FETCH_ERROR";
export const PROPOSAL_FETCH_SUCCESS = "PROPOSAL_FETCH_SUCCESS";

export const SAVE_BID_QUERY = "SAVE_BID_QUERY";

export const SAVE_BID_SUCCESS = "SAVE_BID_SUCCESS";

export const SAVE_BID_ERROR = "SAVE_BID_ERROR";

export const PUBLISH_BID_QUERY = "PUBLISH_BID_QUERY";

export const PUBLISH_BID_SUCCESS = "PUBLISH_BID_SUCCESS";
export const PUBLISH_BID_ERROR = "PUBLISH_BID_ERROR";
export const GET_BIDS_BY_SELLER_QUERY = "GET_BIDS_BY_SELLER_QUERY";
export const BIDS_BY_SELLER_SUCCESS = "BIDS_BY_SELLER_SUCCESS";
export const BIDS_BY_SELLER_ERROR = "BIDS_BY_SELLER_ERROR";
export const GET_BIDS_INFO_QUERY = "GET_BIDS_INFO_QUERY";
export const GET_BID_INFO_SUCCESS = "GET_BID_INFO_SUCCESS";
export const GET_BID_INFO_ERROR = "GET_BID_INFO_ERROR";






